### ISSUE TITLE
LiveTest.testDiscoveryStrategyDiscoverNodesLive

### ISSUE THREAD

**Issue by hasancelik** [hazelcast/hazelcast-azure#4]
```
java.lang.IllegalArgumentException: clientId is null or empty
	at com.microsoft.aad.adal4j.ClientCredential.<init>(ClientCredential.java:41)
	at com.hazelcast.azure.AzureAuthHelper.getAccessTokenFromServicePrincipalCredentials(AzureAuthHelper.java:112)
	at com.hazelcast.azure.AzureAuthHelper.createConfiguration(AzureAuthHelper.java:81)
	at com.hazelcast.azure.AzureAuthHelper.getAzureConfiguration(AzureAuthHelper.java:56)
	at com.hazelcast.azure.integration.LiveTest.deployVirtualMachines(LiveTest.java:98)
```
https://hazelcast-l337.ci.cloudbees.com/view/Plugins/job/Azure-Master/com.hazelcast$hazelcast-azure/22/testReport/junit/com.hazelcast.azure.integration/LiveTest/testDiscoveryStrategyDiscoverNodesLive/

**Comment by mesutcelik** [comment]
`LiveTest` will be used for manual integration testing so closing this one.
